### ISSUE TITLE
Invalid Name

### ISSUE THREAD

**Issue by Temmie19** [IpsumCapra/OpenComputersScripts#1]
When booting it will say
`/main.lua:485: attempt to call field 'name' (a nil value)`

Which is ironic considering that it's checking to see if it's empty. I did check to see if it wasn't declared and it looks fine, so I don't know what the issue is

**Comment by IpsumCapra** [comment]
That's odd. WarpOS still works for me. What versions of OC, Warpdrive and minecraft are you using?

**Comment by Temmie19** [comment]
I'm using the latest version of OC at 1.7.5, but I realized a little later on and just forgot to say anything, but the issue likely occurs because I was on Minecraft 1.7.10, and there was no `core` part. Though I did try renaming it to the `warpdriveShipCore` and also tried `warpdriveShipController` but neither worked.

**Comment by IpsumCapra** [comment]
WarpOS was written for 1.12.2, and doesn't support 1.7.10. The mod has changed a lot since 1.7.10, method names have been changed, others deprecated. This isn't an issue with the code, but with the older version you are using, so i'm closing this issue. Currently i have no plans on making a port for the older version, sorry.

**Comment by Temmie19** [comment]
Hey it's totally cool! No worries

**Comment by IpsumCapra** [comment]
If you'd like help with porting it yourself however, feel free to contact me, i'd be happy to lend a hand.
